FORMAT: 1A
HOST: http://pursuitofhoppyness.me

# Pursuit of Hoppyness
PursuitOfHoppyness is a useful API used to help people find the perfect beer for them which they can search through different breweries and venues as well as specifications of the different beers.  


# group Beers 

## Beer Collection [/beers]

### List All Beers [GET /api/beers]
Retrieve a list of all beers from the PursuitOfHoppyness database.

+ Response 200 (application/json)

        [
            {
              "abv": 5.2, 
              "brewery_id": 259, 
              "ibu": 33, 
              "id": 3558, 
              "label": "https://untappd.akamaized.net/site/beer_logos/beer-3558_fe9a9_sm.jpeg", 
              "name": "Brooklyn Lager", 
              "rating": 3.506, 
              "state_id": "NY", 
              "style": "Lager - Vienna"
            }, 
            {
              "abv": 6.8, 
              "brewery_id": 2228, 
              "ibu": 66, 
              "id": 8238, 
              "label": "https://untappd.akamaized.net/site/beer_logos/beer-IPA_8238.jpeg", 
              "name": "IPA", 
              "rating": 3.541, 
              "state_id": "CA", 
              "style": "IPA - American"
            }, 
            {
              "abv": 8.9, 
              "brewery_id": 39329, 
              "ibu": 32, 
              "id": 249566, 
              "label": "https://untappd.akamaized.net/site/beer_logos/beer-Hellion_249566.jpeg", 
              "name": "Hellion", 
              "rating": 3.652, 
              "state_id": "CA", 
              "style": "Blonde Ale - Belgian Blonde / Golden"
            }
        ]
### Specific Beer [GET /api/beers/{beer_id}]
Retrieve details of a specific beer using its ID from the database including the beer's name, brewery, labels, style, venue, and if it's organic or not.

+ Parameters
    + beer_id (number, required) - the unique id of the beer as an integer
    
+ Response 200 (application/json)

        [
            {
                "abv": 5.2
                "brewery_id": 259,
                "ibu": 33
                "id": "3558",
                "labels": "https://untappd.akamaized.net/site/beer_logos/beer-3558_fe9a9_sm.jpeg",
                "name": "Brooklyn Lager",
                "rating": 3.506
                "state_id": "NY",
                "style": "Lager - Vienna"
                
            }
        ]


# group Brewery 

## Brewery Collection [/brewery]

### List all Breweries [GET /api/breweries]
Retrieve the list of all of the breweries.

+ Response 200 (application/json)

        [
            {
              "address": "369 Congress St, Boston, MA", 
              "brewery_type": "Micro Brewery", 
              "founded": 1893.1081365741, 
              "id": 23038, 
              "label": "https://untappd.akamaized.net/site/brewery_logos/brewery-trillium_23038.jpeg", 
              "name": "Trillium Brewing Company", 
              "state_id": "MA"
            }, 
            {
              "address": "3725 Greenwood St, San Diego, CA", 
              "brewery_type": "Micro Brewery", 
              "founded": 1382.8446643519, 
              "id": 68356, 
              "label": "https://untappd.akamaized.net/site/brewery_logos/brewery-68356_982b4.jpeg", 
              "name": "Modern Times Beer", 
              "state_id": "CA"
            }, 
            {
              "address": "1280 North McDowell Boulevard, Petaluma, CA", 
              "brewery_type": "Micro Brewery", 
              "founded": 2373.8632638889, 
              "id": 765, 
              "label": "https://untappd.akamaized.net/site/brewery_logos/brewery-765_b53eb.jpeg", 
              "name": "Lagunitas Brewing Company", 
              "state_id": "CA"
            }
        ]
        
### Specific Brewery [GET /api/brewery/{brewery_id}]
Retrieve the details of a specific brewery using its ID from the database including its name, brewery type, when it's founded, labels, address, venues, and states.

+ Parameters
    + brewery_id (number, required) - the unique id of the brewery as an integer
    
+ Response 200 (application/json)

        [
            {
                "address": "369 Congress St, Boston, MA",
                "brewery_type": "Micro Brewery",
                "founded": 1893.1081365741,
                "id": 23038,
                "label": "https://untappd.akamaized.net/site/brewery_logos/brewery-trillium_23038.jpeg",
                "name": "Trillium Brewing Company",
                "state_id": "MA"
            }
        ]


# group Venue 

## All Venues [/venue]

###List all Venues [GET /api/venues]
Retrieve the list of all of the venues.

+ Response 200 (application/json)

        [
            {
              "address": "10426 National Blvd, Los Angeles, CA", 
              "category": "Mexican Restaurant", 
              "id": 6, 
              "is_public": true, 
              "media": "https://untappd.akamaized.net/photo/2016_08_25/903644606c381723486b7bc34135430b_raw.jpeg", 
              "name": "El Nopal", 
              "state_id": "CA"
            }, 
            {
              "address": "2 Boland Way, Springfield, MA", 
              "category": "Hotel", 
              "id": 7, 
              "is_public": true, 
              "media": "https://untappd.akamaized.net/photo/2017_04_01/44ba60270c1c6b5cb763ccaf83caa746_raw.jpg", 
              "name": "Springfield Marriott", 
              "state_id": "MA"
            }, 
            {
              "address": "1277 Main St, Springfield, MA", 
              "category": "Hockey Arena", 
              "id": 10, 
              "is_public": true, 
              "media": "https://untappd.akamaized.net/photo/2017_04_01/049590f461ccc18a9594b10d23947813_raw.jpeg", 
              "name": "MassMutual Center", 
              "state_id": "MA"
            }
        ]

### Specific Venue [GET /api/venue/{venue_id}]
Retrieve the specific details of a venue using its ID from the database includings its name, media, address, category, state, breweries, and beers.

+ Parameters
    + venue_id (number, required) - the unique id of the venue as an integer
    
+ Response 200 (application/json)

        [
            {
                "address": "10426 National Blvd, Los Angeles, CA", 
                "category": "Mexican Restaurant", 
                "id": 6, 
                "is_public": true, 
                "media": "https://untappd.akamaized.net/photo/2016_08_25/903644606c381723486b7bc34135430b_raw.jpeg", 
                "name": "El Nopal", 
                "state_id": "CA"
            }
        ]


# group State 

## State Collection [/state]

### List all States [GET /api/states]
Retrieves a list of all of the states and their abbreviationsixe.
    
+ Response 200 (application/json)

        [
            {
              "abbreviation": "AL", 
              "capital": "Montgomery", 
              "flower": "Camellia", 
              "media": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Alabama.svg/300px-Flag_of_Alabama.svg.png", 
              "name": "Alabama"
            }, 
            {
              "abbreviation": "AK", 
              "capital": "Juneau", 
              "flower": "Forget-me-not", 
              "media": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Alaska.svg/286px-Flag_of_Alaska.svg.png", 
              "name": "Alaska"
            }, 
            {
              "abbreviation": "AS", 
              "capital": "Phoenix", 
              "flower": "Saguaro cactus blossom", 
              "media": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Arizona.svg/300px-Flag_of_Arizona.svg.png", 
              "name": "Arizona"
            }
        ]
        
### Specific States [GET /api/state/{state_abbreviation}]
Retrieves the specific details of a location using its ID from the database including its name, capital, and media.

+ Parameters
    + state_abbreviation (string, required) - the unique abbreviation of the state as a string

+ Response 200 (application/json)

        [
            {
                "abbreviation": "TX",
                "capital": "Austin",
                "flower": "Bluebonnet",
                "media": "https://en.wikipedia.org/wiki/Flag_of_Texas#/media/File:Flag_of_Texas.svg",
                "name": "Texas"
            }
        
        ]